#use volumes for fe dist code
version: '3'
services:
  webapp:
    build: ./web
    ports:
      - "5000:5000"
    volumes:
      - "./web:/code"
      - "static:/code/static"
  webpack:
    build:
      context: ./web
      dockerfile: Dockerfile.webpack
    volumes:
       - "static:/code/static"
       - "./web/frontend:/code/frontend"
  database:
    build: ./database
    ports:
      - "27017:27017"
    volumes:
      - "./database/data:/data/db"
      - "./database/scripts:/data/scripts"
volumes:
  static: