version: '3'
services:
  webpack:
    build:
      context: ./web
      dockerfile: Dockerfile.webpack
    volumes:
       - "./web/static:/code/static"
       - "./web/frontend:/code/frontend"
    command: ["npm","run","watch"]
    #command: ls